[run]
build = "npm run build"

[gptengineer-app]
project_id = "e2bfac9a-be47-4a21-9c7e-f65bcbdc5283"

[[gptengineer-app.openapi]]
url = "https://mnwefvnykbgyhbdzpleh.supabase.co/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ud2Vmdm55a2JneWhiZHpwbGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTMyNzQ3MzQsImV4cCI6MjAyODg1MDczNH0.tnHysd1LqayzpQ1L-PImcvlkUmkNvocpMS7tS-hYZNg"
